[pytest]
# Add default command line arguments here
# --headed: Opens the browser so you can see it
# --browser chromium: Uses Chrome engine
# --slowmo 500: Slows down actions by 0.5s so you can follow along
# -s: Disable output capture to see print statements in the console
addopts = --headed --browser chromium --slowmo 500 -s

# Tell pytest where to look for tests
testpaths = tests

# Define patterns for test files and methods
python_files = test_*.py
python_functions = test_*